image: docker:stable

variables:
   DOCKER_HOST: tcp://docker:2375/
   DOCKER_DRIVER: overlay2

stages:
  - build
  - push

services:
  - docker:dind

docker build:
  stage: build
  script:
  - docker info
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker build -t $CI_REGISTRY/edugon/chappie .

docker push:
  stage: push
  only:
  - master
  script:
    - docker push $CI_REGISTRY/edugon/chappie