image: docker:stable

variables:
  - DOCKER_HOST: tcp://docker:2375
  - DOCKER_DRIVER: overlay2

stages:
  - Build image
  - Push to Docker Hub

docker build:
  stage: Build image
  script:
  - docker info
  - docker build -t chappie .

docker push:
  stage: Push to Docker Hub
  only:
  - master
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY/edugon/chappie .
    - docker push $CI_REGISTRY/edugon/chappie