image: docker:stable

variables:
   DOCKER_HOST: tcp://docker:2375/
   DOCKER_DRIVER: overlay2

stages:
  - push

services:
  - docker:dind

docker:
  stage: push
  only:
  - master
  script:
  - docker info
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  - docker build -t $CI_REGISTRY/edugon/chappie .
  - docker push $CI_REGISTRY/edugon/chappie
  tags:
    - docker